version: '3.9'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: todo-app-tg-bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345burma
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
